[workspace]
members = ["crates/*"]
exclude = ["vendor/oxc"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.95"

[workspace.metadata.vidact.react-compiler]
repository = "https://github.com/oxc-project/oxc"
crate-version = "0.143.0"
revision = "45a17c25d188bf1b289638483e2bc61adbadd364"
vendored-path = "vendor/oxc"
patches-path = "patches/oxc"
git-go-patch-module-version = "v0.0.16"
git-go-patch-tool-version = "v1.0.1"
react-rust-pull-request = 36173

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
