// oxlint-disable-next-line typescript/triple-slash-reference -- Include the build define in consuming TypeScript programs.
/// <reference path="./env.d.ts" />
export { combineSources, intersectsSources, source, type SourceMask } from './source-mask.ts'
export type { StateUpdate } from './state-slot.ts'
export {
  createElement,
  Fragment,
  h,
  type DirectChild,
  type DirectComponent,
  type DirectProps,
} from './direct-dom.ts'
export { useRef, type MutableRef } from './ref.ts'
export { createRoot, mountHotRoot, type CompiledRoot, type HotContext } from './root.ts'
export { assertRuntimeProtocol, VIDACT_RUNTIME_PROTOCOL } from './protocol.ts'
export { compiledSpread } from './spread.ts'
export { compiledComponentSpread } from './component-spread.ts'
export {
  cloneRenderable,
  cloneRenderableComponent,
  createReactElement,
  createRenderable,
  dynamicIntrinsicComponent,
  forwardedRef,
  isRenderable,
  renderableChildren,
  renderableMarker,
  renderableProps,
  renderableRef,
  renderableToArray,
  type CompiledRenderable,
  type RenderablePropsInput,
} from './renderable.ts'
export { nestedProp } from './nested-prop.ts'
export {
  binding,
  choose,
  compiledEvent,
  compiledEffect,
  compiledImperativeHandle,
  compiledInsertionEffect,
  compiledLayoutEffect,
  compiledRoot,
  createPortal,
  createCompiledContext,
  createCompiledEffectEvent,
  createCompiledExternalStore,
  createCompiledId,
  createCompiledMemo,
  createCompiledProp,
  createCompiledReducer,
  createCompiledRestProp,
  createCompiledScope,
  createNarrowCompiledScope,
  createCompiledState,
  createContext,
  dispatch,
  deferred,
  indexed,
  keyed,
  errorBoundary,
  mountCompiled,
  mountCompiledRef,
  useCallback,
  use,
  useContext,
  useEffect,
  useEffectEvent,
  useImperativeHandle,
  useInsertionEffect,
  useId,
  useLayoutEffect,
  useMemo,
  useSyncExternalStore,
  when,
  type CompiledBinding,
  type CompiledComponentResult,
  type CompiledContext,
  type CompiledErrorHandler,
  type CompiledRenderValue,
  type CompiledScope,
  type MountCompiledOptions,
  type ChoiceMode,
  type OwnedBlock,
  type StructuralBinding,
} from './compiled.ts'
